include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "test/.test_coverage.dart"
    - "lib/generated_plugin_registrant.dart"

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    omit_local_variable_types: false
    always_specify_types: false
    eol_at_end_of_file: false
    prefer_constructors_over_static_methods: false
    require_trailing_commas: false
    sort_constructors_first: false
    no_default_cases: false
    avoid_redundant_argument_values: false
    avoid_bool_literals_in_conditional_expressions: false
    prefer_relative_imports: true
    depend_on_referenced_packages: false
    avoid_positional_boolean_parameters: false